"""empty message

Revision ID: a54159a01f81
Revises: 9df62c42cbf6
Create Date: 2021-12-01 00:01:58.559168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54159a01f81'
down_revision = '9df62c42cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_constraint('place_id_post_fkey', 'place', type_='foreignkey')
    op.drop_column('place', 'id_post')
    op.drop_constraint('posts_id_review_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'id_review')
    op.drop_column('services', 'geom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('id_review', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_id_review_fkey', 'posts', 'reviews', ['id_review'], ['id'])
    op.add_column('place', sa.Column('id_post', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('place_id_post_fkey', 'place', 'posts', ['id_post'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
